version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/app
    ports:
      - '27081:80'
    container_name: wxcloud_export
    labels:
      - wxPort=27082
      - hostPort=27081
      - wxcloud=export
      - role=container
    environment:
      - MYSQL_USERNAME=
      - MYSQL_PASSWORD=
      - MYSQL_ADDRESS=
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=4mEW3XNw
      - MYSQL_ADDRESS=10.19.110.233:3306
networks:
  default:
    external:
      name: wxcb0
